# Generated by Django 6.0.2 on 2026-05-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_unique_doctor_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='category',
            field=models.CharField(default='Check-up', max_length=50),
        ),
    ]
