/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./test/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1b1d",
        "on-primary-container": "#7d839a",
        "on-primary-fixed": "#151b2d",
        "primary-container": "#151b2d",
        "on-error-container": "#93000a",
        "on-surface-variant": "#46464c",
        "secondary-fixed-dim": "#68dba9",
        "inverse-on-surface": "#f3f0f2",
        "inverse-surface": "#303032",
        "primary-fixed": "#dce1fb",
        "surface-tint": "#585e73",
        "tertiary-container": "#2a1700",
        "tertiary": "#000000",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#005137",
        "on-background": "#1b1b1d",
        "on-tertiary-fixed-variant": "#653e00",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e5e2e3",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary-container": "#b87500",
        "on-tertiary-fixed": "#2a1700",
        "on-primary": "#ffffff",
        "surface": "#fcf8fa",
        "on-secondary-container": "#00714e",
        "surface-bright": "#fcf8fa",
        "primary-fixed-dim": "#c0c6de",
        "on-primary-fixed-variant": "#40465a",
        "inverse-primary": "#c0c6de",
        "primary": "#000000",
        "on-error": "#ffffff",
        "surface-container": "#f0edef",
        "surface-container-low": "#f6f3f4",
        "error": "#ba1a1a",
        "outline": "#76767d",
        "surface-dim": "#dcd9db",
        "surface-variant": "#e5e2e3",
        "on-tertiary": "#ffffff",
        "secondary-container": "#82f5c1",
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary-fixed": "#002114",
        "background": "#fcf8fa",
        "secondary-fixed": "#85f8c4",
        "on-secondary": "#ffffff",
        "secondary": "#006c4a",
        "surface-container-high": "#eae7e9",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "container-padding": "32px",
        "section-gap": "64px",
        "element-gap": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-sm": ["Manrope", "sans-serif"],
        "h2": ["Manrope", "sans-serif"],
        "h1": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "h3": ["Manrope", "sans-serif"],
        "sans": ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
